#!/Library/Frameworks/Python.framework/Versions/3.7/bin/python3
import sys

if len(sys.argv) <= 1: #if there is no argument passed
    print ("")
    print ("This script will turn a csv file into the correct format for DNS Made Easy.")
    print ("--- Incorrect Syntax ----")
    print ("Usage: aRecordsCsv <zone csv>")
    print ("Example: aRecordsCsv dnsmadeeasy.csv")
    print ("")
else:
    file=sys.argv[2] #grab file from first argument
    print('$ORIGIN {}'.format(sys.argv[1]))
    with open(file) as dbfile:
        for line in dbfile: #run file line by line
            name,IP=line.split(',')
            name=name.replace('.{}'.format(sys.argv[1]),'')#strip root from FQDN
            name=name.replace('{}'.format(sys.argv[1]),'') #don't have root 
            if name == '':
                name='@'
            IP=IP.strip('\n')
            print ('{}\t1800\tIN\tA\t{}'.format(name,IP))