#!/Library/Frameworks/Python.framework/Versions/3.7/bin/python3
import sys

if len(sys.argv) <= 1: #if there is no argument passed
    print ("")
    print ("This script will turn a csv file into the correct format for DNS Made Easy.")
    print ("--- Incorrect Syntax ----")
    print ("Usage: csvToZone <domain name> <zone csv>")
    print ("Example: csvToZone dnsmadeeasy.com dnsmadeeasy.csv")
    print ("")
else:
    file=sys.argv[2] #grab file from first argument
    print('$ORIGIN {}'.format(sys.argv[1]))
    with open(file) as dbfile:
        for line in dbfile: #run file line by line
            type,domain,name,value=line.split(',')
            if name == '':
                name='@'
            value=value.strip('\n')
            if type == "TXT":
                print ('{}\t1800\tIN\t{}\t"{}"'.format(name,type,value))
            else:
                print ('{}\t1800\tIN\t{}\t{}'.format(name,type,value))