#!/bin/bash

if [ $# -lt 1 ]; then
	echo ""
	echo "This script will run a list of domains or a singluar domain against their respective TLD's to show you their delegated name servers."
	echo "--- Incorrect Syntax ----"
	echo "Usage: tldns <file of domains/domain>"
	echo "Example: tldns dnsmadeeasy.txt"
	echo "Example: tldns constellix.com" 
	echo ""
	exit
fi

if [ -f $1 ]; then
	for x in `grep -v ^# $1 | awk '{print $1}'`; do
		echo "nameservers for $x"
		NAMESERVERS=`dig ns $x @f.root-servers.net +trace +noanswer | grep $x | grep 'IN\sNS' | awk '{print $5}' | sort | uniq`
		if [[ $NAMESERVERS ]]; then
			echo "$NAMESERVERS"
			echo ""
		else
			echo "None"
			echo ""
	fi
	done
else
	echo "nameservers from $TLD for $1"
	NAMESERVERS=`dig ns $1 @f.root-servers.net +trace +noanswer | grep $1 | grep 'IN\sNS' | awk '{print $5}' | sort | uniq`
	if [[ $NAMESERVERS ]]; then
		echo "$NAMESERVERS"
		echo ""
	else
		echo "None"
		echo ""
	fi
fi