#!/bin/bash
if [ $# -lt 1 ]; then
	echo ""
	echo "This script will see who owns the IP of a name server to check for VanityDNS."
	echo "--- Incorrect Syntax ----"
	echo "Usage: vanityCheck <domain name>"
	echo "Example: vanityCheck kalebbarton.com"
	echo ""
	exit
fi
nameservers=`dig +short ns $1`
for nameserver in $nameservers; do
    ip=`dig +short a $nameserver`
        org=`whois $ip | grep OrgName: | sed 's/OrgName://g'`
    if [ -z "$org" ]; then
        org=`whois $ip | grep org-name | sed 's/org-name://g'`
    fi
    if [ -z "$org" ]; then
        org=`whois $ip | grep netname: | sed 's/netname://g'`
    fi
    echo $nameserver is owned by $org
done